package com.robertboothby.djenni.util;

import com.robertboothby.djenni.ConfigurableSupplierBuilder;
import com.robertboothby.djenni.SupplierBuilder;
import com.robertboothby.djenni.core.StreamableSupplier;

import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.Objects;
import java.util.TimeZone;
import java.util.function.Supplier;

/**
 * Builds suppliers of {@link Calendar}. Dates default to those generated by {@link DateSupplierBuilder} and the default
 * zone is {@link ZoneId#systemDefault()}.
 */
public class CalendarSupplierBuilder implements ConfigurableSupplierBuilder<Calendar, CalendarSupplierBuilder> {

    private Supplier<Date> dateSupplier = DateSupplierBuilder.dateSupplier().build();
    private Supplier<ZoneId> zoneSupplier = ZoneId::systemDefault;

    public static CalendarSupplierBuilder calendarSupplier() {
        return new CalendarSupplierBuilder();
    }

    @Override
    public StreamableSupplier<Calendar> build() {
        Supplier<Date> actualDateSupplier = this.dateSupplier;
        Supplier<ZoneId> actualZoneSupplier = this.zoneSupplier;
        return () -> {
            Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone(actualZoneSupplier.get()));
            calendar.setTime(actualDateSupplier.get());
            return calendar;
        };
    }

    public CalendarSupplierBuilder dateSupplier(Supplier<Date> supplier) {
        this.dateSupplier = Objects.requireNonNull(supplier, "supplier");
        return this;
    }

    public CalendarSupplierBuilder dateSupplier(SupplierBuilder<Date> builder) {
        Objects.requireNonNull(builder, "builder");
        return dateSupplier(builder.build());
    }

    public CalendarSupplierBuilder zoneSupplier(Supplier<ZoneId> supplier) {
        this.zoneSupplier = Objects.requireNonNull(supplier, "supplier");
        return this;
    }
}
