package com.robertboothby.djenni.core;

import com.robertboothby.djenni.Generator;
import org.hamcrest.Description;

import java.util.List;

/**
 * This Generator concatenates the {@link Object#toString()} values of the values generated by the individual generators
 * to create its output. The sequence of concatenation is simply determined by the order of the Generator list passed at
 * construction time.
 */
public class ConcatenatingStringGenerator implements Generator<String> {

    private final List<Generator<? extends Object>> generators;

    /**
     * Construct an instance of this generator using the passed in generators.
     * @param generators the generator to use.
     */
    public ConcatenatingStringGenerator(List<Generator<? extends Object>> generators) {
        this.generators = generators;
    }

    @Override
    public String generate() {
        StringBuilder stringBuilder = new StringBuilder();
        for(Generator generator : generators) {
            stringBuilder.append(generator.generate());
        }
        return stringBuilder.toString();
    }

    @Override
    public void describeTo(Description description) {
        description.appendText("ConcatenatingStringGenerator : { ");
        description.appendList("[",", ", "]",  generators);
        description.appendText(" }");
    }

}
