package com.robertboothby.djenni.core;

import com.robertboothby.djenni.Generator;
import org.hamcrest.Description;

import java.util.List;

/**
 * This Generator concatenates the {@link Object#toString()} values of the values generated by the individual generators
 * to create its output. The sequence of concatenation is simply determined by the order of the Generator list passed at
 * construction time.
 * <p>&#169; 2014 Forest View Developments Ltd.</p>
 *
 * @author robertboothby
 */
public class ConcatenatingStringGenerator implements Generator<String> {

    private final List<Generator<String>> generators;

    public ConcatenatingStringGenerator(List<Generator<String>> generators) {
        this.generators = generators;
    }

    @Override
    public String generate() {
        StringBuilder stringBuilder = new StringBuilder();
        for(Generator generator : generators) {
            stringBuilder.append(generator.generate());
        }
        return stringBuilder.toString();
    }

    @Override
    public void describeTo(Description description) {
        description.appendText("{ ConcatenatingStringGenerator : { ");
        for(Generator generator : generators) {
            generator.describeTo(description);
            description.appendText(", ");
        }
        description.appendText("}");
    }

}
