package com.robertboothby.djenni;

/**
 * Marker interface for all GeneratorBuilder instances that produce SerializableGenerators.
 * <p>&#169; 2013 Forest View Developments Ltd.</p>
 * @author robertboothby
 * @param <T> The type of the value that will be generated by the configured Generator.
 */
public interface SerializableGeneratorBuilder<T> extends GeneratorBuilder<T>{

    SerializableGenerator<T> build();
}
